import {
    PlaneTakeoff,
    GraduationCap,
    Gamepad2,
    Briefcase,
    Heart,
    Home,
    Tag,
    Rocket,
    PartyPopper,
    Star,
    PawPrint,
    Car,
    Utensils,
    Dumbbell,
    Hospital,
    Landmark,
    Lightbulb,
    Zap,
    Flower2,
    Mountain,
    Feather,
    Calendar,
    Hourglass,
    StopCircle,
    Pencil,
    TrendingUp,
    CalendarDays,
    Timer,
    Radar,
    Infinity,
    Wallet,
    Clock,
    Plus,
    X,
    CalendarRange,
    ArrowRight,
    Info,
    PlayCircle,
    CalendarClock,
    HelpCircle,
    History,
    Settings,
    Trash,
    BookOpen,
    Check
} from 'lucide-svelte';

export enum IconType {
    DELETE = 'delete',
    SETTINGS = 'settings',
    FLIGHT_TAKEOFF = 'flight_takeoff',
    SCHOOL = 'school',
    TOYS = 'toys',
    WORK = 'work',
    FAVORITE = 'favorite',
    HOME = 'home',
    LABEL = 'label',
    ROCKET_LAUNCH = 'rocket_launch',
    CELEBRATION = 'celebration',
    STAR = 'star',
    PETS = 'pets',
    DIRECTIONS_CAR = 'directions_car',
    RESTAURANT = 'restaurant',
    FITNESS_CENTER = 'fitness_center',
    LOCAL_HOSPITAL = 'local_hospital',
    ACCOUNT_BALANCE = 'account_balance',
    LIGHTBULB = 'lightbulb',
    BOLT = 'bolt',
    SPA = 'spa',
    HIKING = 'hiking',
    HISTORY_EDU = 'history_edu',
    CALENDAR_MONTH = 'calendar_month',
    TIMELAPSE = 'timelapse',
    STOP_CIRCLE = 'stop_circle',
    EDIT = 'edit',
    INSIGHTS = 'insights',
    CALENDAR_VIEW_WEEK = 'calendar_view_week',
    TIMER = 'timer',
    TRACK_CHANGES = 'track_changes',
    ALL_INCLUSIVE = 'all_inclusive',
    ACCOUNT_BALANCE_WALLET = 'account_balance_wallet',
    SCHEDULE = 'schedule',
    ADD = 'add',
    CLOSE = 'close',
    DATE_RANGE = 'date_range',
    SELL = 'sell',
    ARROW_RIGHT_ALT = 'arrow_right_alt',
    INFO = 'info',
    ARROW_FORWARD = 'arrow_forward',
    PLAY_CIRCLE = 'play_circle',
    CALENDAR_CLOCK = 'calendar_clock',
    HELP = 'help',
    HISTORY = 'history',
    CHILDHOOD = 'childhood',
    VACATION = 'vacation',
    EDUCATION = 'education',
    CAREER = 'career',
    HEALTH = 'health',
    FAMILY = 'family',
    STARS = 'stars',
    BOOK_OPEN = 'book_open',
    CHECK = 'check',
}

export const iconMap: Record<IconType, any> = {
    'delete': Trash,
    'settings': Settings,
    'flight_takeoff': PlaneTakeoff,
    'school': GraduationCap,
    'toys': Gamepad2,
    'work': Briefcase,
    'favorite': Heart,
    'home': Home,
    'label': Tag,
    'rocket_launch': Rocket,
    'celebration': PartyPopper,
    'star': Star,
    'pets': PawPrint,
    'directions_car': Car,
    'restaurant': Utensils,
    'fitness_center': Dumbbell,
    'local_hospital': Hospital,
    'account_balance': Landmark,
    'lightbulb': Lightbulb,
    'bolt': Zap,
    'spa': Flower2,
    'hiking': Mountain,
    'history_edu': Feather,
    'calendar_month': Calendar,
    'timelapse': Hourglass,
    'stop_circle': StopCircle,
    'edit': Pencil,
    'insights': TrendingUp,
    'calendar_view_week': CalendarDays,
    'timer': Timer,
    'track_changes': Radar,
    'all_inclusive': Infinity,
    'account_balance_wallet': Wallet,
    'schedule': Clock,
    'add': Plus,
    'close': X,
    'date_range': CalendarRange,
    'sell': Tag,
    'arrow_right_alt': ArrowRight,
    'info': Info,
    'arrow_forward': ArrowRight,
    'play_circle': PlayCircle,
    'calendar_clock': CalendarClock,
    'help': HelpCircle,
    'history': History,
    'childhood': Gamepad2,
    'vacation': PlaneTakeoff,
    'education': GraduationCap,
    'career': Briefcase,
    'health': Heart,
    'family': Home,
    'stars': Star,
    'book_open': BookOpen,
    'check': Check
};

export const availableIcons = Object.keys(iconMap) as IconType[];
